Update custom-functions guide
handsontable/hyperformula pull request #1000
Opened 2022-06-01 08:25 UTC by sequba

### Context

TBP

### How has this been tested?

TBP

### Types of changes

- [x] Docs

### Related issue(s):
1. Fixes #968 
2.
3.

### Checklist:

- [x] My code follows the code style of this project,
- [ ] My change requires a change to the documentation,
- [ ] I described the modification in the CHANGELOG.md file.

2022-06-04 15:19 UTC, sequba commented on src/interpreter/plugin/FunctionPlugin.ts
> +    let argumentDefinitions: FunctionArgument[] = metadata.parameters || []
This is a bugfix. Our documentation says that `parameters` field is optional, but this function fails when it's not defined.

2022-06-10 08:44 UTC, kirszenbaum requested changes
@sequba – I added my suggestions in #1010

2022-06-10 11:00 UTC, sequba commented
@kirszenbaum suggestions applied.

2022-06-10 11:50 UTC, kirszenbaum requested changes

2022-06-10 11:50 UTC, kirszenbaum commented on docs/guide/custom-functions.md
> +Expand the function library of your application by adding custom functions.
```suggestion
Expand the function library of your application, by adding custom functions.
```

Let's leave the comma here.

2022-06-10 11:50 UTC, kirszenbaum commented on docs/guide/custom-functions.md
> +For example, let's create a function that returns the number of letters in the word "HyperFormula".
```suggestion
As an example, let's create a function that returns the number of letters in the word "HyperFormula".
```

2022-06-10 11:50 UTC, kirszenbaum commented on docs/guide/custom-functions.md
> +Add a method that implements your function's calculations in your function plugin. Your method needs to:
```suggestion
In your function plugin, add a method that implements your function's calculations. Your method needs to:
```

Location comes first, action second.

2022-06-10 11:50 UTC, kirszenbaum commented on docs/guide/custom-functions.md
> +In your function plugin, in the static `implementedFunctions` property, next to other options, add an array called `parameters`:
```suggestion
In your function plugin, in the static `implementedFunctions` property, next to other options add an array called `parameters`:
```

2022-06-10 11:50 UTC, kirszenbaum commented on docs/guide/custom-functions.md
> +The `defaultValue` and `optionalArg` options let you decide what happens when a user doesn't pass enough valid arguments to your custom function.
```suggestion
Both the `defaultValue` and `optionalArg` options let you decide what happens when a user doesn't pass enough valid arguments to your custom function.
```

2022-06-10 11:57 UTC, kirszenbaum approved these changes

2022-06-10 12:16 UTC, merged