Fix documentation about the SPLIT function
handsontable/hyperformula pull request #1039
Opened 2022-07-27 11:46 UTC by sequba

### Context

- Update description in the built-in-functions guide
- Mention it in the known-limitations guide

### How has this been tested?

Local docs build

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Additional language file or change to the existing one (translations)
- [x] Change to the documentation

### Related issues:
1. Fixes #1035 
2.
3.

### Checklist:

- [x] My code follows the code style of this project.
- [ ] I described the modification in the CHANGELOG.md file.
- [ ] My change requires a change to the documentation.
- [ ] My change requires a migration guide.

2022-08-04 10:07 UTC, warpech requested changes
LGTM, just some grammar suggestions

2022-08-04 10:07 UTC, warpech commented on docs/guide/known-limitations.md
> +| SPLIT function                                     | =SPLIT("Lorem ipsum dolor", 0)                                            | This function works differently from Google Sheets version but shoul
```suggestion
| SPLIT function                                     | =SPLIT("Lorem ipsum dolor", 0)                                            | This function works differently from Google Sheets version but should be sufficient to achieve the same functionality in most scenarios. Read SPLIT function description on [the Built-in Functions page](built-in-functions.html#text).                                                               | Different syntax and return value.                                                                                                | No such function.                                        |
```

2022-08-04 10:07 UTC, warpech commented on docs/guide/built-in-functions.md
> +| SPLIT         | Divides the provided text using space character as a separator and returns the substring at zero-based position specified by the second argument.<br>```SPLIT("Lorem ipsum", 0) -> "L
```suggestion
| SPLIT         | Divides the provided text using the space character as a separator and returns the substring at the zero-based position specified by the second argument.<br>```SPLIT("Lorem ipsum", 0) -> "Lorem"```<br>```SPLIT("Lorem ipsum", 1) -> "ipsum"``` | SPLIT(Text; Index)                                 |
```

2022-08-04 11:44 UTC, sequba commented on docs/guide/known-limitations.md
> +| SPLIT function                                     | =SPLIT("Lorem ipsum dolor", 0)                                            | This function works differently from Google Sheets version but shoul
suggestion applied

2022-08-04 11:45 UTC, sequba commented on docs/guide/built-in-functions.md
> +| SPLIT         | Divides the provided text using space character as a separator and returns the substring at zero-based position specified by the second argument.<br>```SPLIT("Lorem ipsum", 0) -> "L
suggestion applied

2022-08-05 08:15 UTC, warpech approved these changes

2022-08-08 09:46 UTC, merged