Docs: Compatibility page review
handsontable/hyperformula pull request #1054
Opened 2022-09-05 13:16 UTC by kirszenbaum

This PR:
- Adds suggestions for the new Compatibility page (added in #1048)

2022-09-05 20:07 UTC, kirszenbaum commented
@sequba - this PR contains my ideas for the compatibility content

- As you said we're considering adding some forms of integration in the future, I went for the "compatibility" term after all
- The **Separators** section basically says consistency with Excel is not possible, so I moved it lower (not to start with bad news)
- I know adding the Google Sheets page changes the scope, but we can fill in  more details later, using the same pattern as on the Excel page (in the meantine, I added what I could check on my own)

2022-09-06 09:26 UTC, sequba requested changes

2022-09-06 09:26 UTC, sequba commented on docs/guide/compatibility-with-google-sheets.md
> +To set up HyperFormula in the same way as Excel's `en-US` locale, use this configuration:
```suggestion
To set up HyperFormula in the same way as Google Sheet's `en-US` locale, use this configuration:
```

2022-09-06 09:30 UTC, sequba commented
I like the idea of separate pages for "Compatibility with Microsoft Excel" and "Compatibility with Google Sheets". @warpech WDYT?

2022-09-06 09:48 UTC, sequba requested changes

2022-09-06 09:48 UTC, sequba commented on docs/guide/compatibility-with-google-sheets.md
> +```
```suggestion
In Google Sheets, the [array arithmetic mode](arrays.md#array-arithmetic-mode) is disabled by default.

To set up HyperFormula in the same way, set the [`useArrayArithmetic`](../api/interfaces/configparams.md#usearrayarithmetic) option to `false`.

```js
useArrayArithmetic: false, // set by default
```
```

2022-09-06 09:48 UTC, sequba commented on docs/guide/compatibility-with-google-sheets.md
> +smartRounding: true, // set by default
Syntax highlighting looks better this way

```suggestion
const options = {
  functionArgSeparator: ',', // set by default
  decimalSeparator: '.', // set by default
  thousandSeparator: '', // set by default
  arrayColumnSeparator: ',', // set by default
  arrayRowSeparator: ';', // set by default
  dateFormats: ['MM/DD/YYYY', 'MM/DD/YY', 'YYYY/MM/DD'],
  timeFormats: ['hh:mm', 'hh:mm:ss.sss'], // set by default
  nullYear: 30, // set by default
  localeLang: 'en', // set by default
  useArrayArithmetic: true,
  leapYear1900: false, // set by default
  smartRounding: true, // set by default
};
```

2022-09-06 14:25 UTC, sequba approved these changes
Thanks @kirszenbaum. I'm merging it.

2022-09-06 14:27 UTC, merged