Create importing-files guide
handsontable/hyperformula pull request #1091
Opened 2022-11-08 16:23 UTC by sequba

### Context

TBP

### How did you test your changes?

- [ ] unit tests pass
- [ ] local docs build
- [ ] code example tested on simple spreadsheet

### Types of changes

- [ ] Breaking change (a fix or a feature because of which an existing functionality doesn't work as expected anymore)
- [ ] New feature or improvement (a non-breaking change that adds functionality)
- [ ] Bug fix (a non-breaking change that fixes an issue)
- [ ] Additional language file, or a change to an existing language file (translations)
- [x] Change to the documentation

### Related issues:
Fixes #992 

### Checklist:

- [x] My change is compliant with the [OpenDocument](https://docs.oasis-open.org/office/OpenDocument/v1.3/os/part4-formula/OpenDocument-v1.3-os-part4-formula.html) standard.
- [x] My change is compatible with Microsoft Excel.
- [x] My change is compatible with Google Sheets.
- [x] My code follows the code style of this project.
- [ ] I described my changes in the [CHANGELOG.md](https://github.com/handsontable/hyperformula/blob/master/CHANGELOG.md) file.
- [ ] My changes require a documentation update.
- [ ] My changes require a migration guide.

2022-11-14 22:09 UTC, warpech requested changes
Great job! I have some text editing proposals

2022-11-15 15:46 UTC, sequba commented on docs/.vuepress/config.js
> +            ['/guide/importing-files', 'Importing XLSX/CSV files'],
Ok, if it makes more sens to you, it might as well be in 'Advanced topics'.

2022-11-15 15:54 UTC, sequba commented on docs/guide/importing-files.md
> +```
Ok, I added the github link

2022-11-15 15:56 UTC, sequba commented on docs/guide/importing-files.md
> +[ExcelJS](https://www.npmjs.com/package/exceljs) library can also read CSV files.
Ok, I changed it as suggested but I put this paragraph in the previous section. It makes more sense this way.

2022-11-15 16:09 UTC, warpech commented on docs/guide/importing-files.md
> +HyperFormula itself has no file import functionality. If you want to work with XLSX or CSV files, you need to use one of the [file parsing libraries](https://www.npmjs.com/search?q=xlsx) and then pas
Fair enough, thanks!

2022-11-15 16:09 UTC, warpech approved these changes

2022-11-15 16:34 UTC, merged