Document the return types of functions EDATE, EOMONTH, DATEVALUE, TIMEVALUE
handsontable/hyperformula pull request #1107
Opened 2022-11-22 10:51 UTC by sequba

### Context

TBP

### How did you test your changes?

TBP

### Types of changes

- [ ] Breaking change (a fix or a feature because of which an existing functionality doesn't work as expected anymore)
- [ ] New feature or improvement (a non-breaking change that adds functionality)
- [ ] Bug fix (a non-breaking change that fixes an issue)
- [ ] Additional language file, or a change to an existing language file (translations)
- [x] Change to the documentation

### Related issues:
Fixes #1101

### Checklist:

- [ ] My change is compliant with the [OpenDocument](https://docs.oasis-open.org/office/OpenDocument/v1.3/os/part4-formula/OpenDocument-v1.3-os-part4-formula.html) standard.
- [ ] My change is compatible with Microsoft Excel.
- [ ] My change is compatible with Google Sheets.
- [x] My code follows the code style of this project.
- [ ] I described my changes in the [CHANGELOG.md](https://github.com/handsontable/hyperformula/blob/master/CHANGELOG.md) file.
- [ ] My changes require a documentation update.
- [ ] My changes require a migration guide.

2022-12-04 23:24 UTC, warpech requested changes
See some ideas about presenting it in a milder and more consistent way. 

Thanks for adding more the tests!

2022-12-04 23:24 UTC, warpech commented on docs/guide/built-in-functions.md
> +| EOMONTH          | Returns the date of the last day of a month which falls months away from the start date. Returns the value in the form of number of full days since [nullDate](../api/interfaces/c
I think the presented note is too horrifying.

WDYT about keeping the long explanation on the other page, and replacing the text here with a simple link:

> [See compatibility notes](list-of-differences.md)

Or even a footnote.

---

I think that, in fact, we could add this for *all* or *none* of the functions listed here that have an entry on the "List of differences" page.

2022-12-04 23:24 UTC, warpech commented on docs/guide/list-of-differences.md
> +| DATEVALUE function                                 | =DATEVALUE("25/02/1991")                                                  | Type of the returned value: `CellValueDetailedType.NUMBER_DATE` (com
```suggestion
| DATEVALUE function                                 | =DATEVALUE("25/02/1991")                                                  | Type of the returned value: `CellValueDetailedType.NUMBER_DATE` (compliant with the [OpenDocument](https://docs.oasis-open.org/office/OpenDocument/v1.3/os/part4-formula/OpenDocument-v1.3-os-part4-formula.html) standard)            | Cell auto-formatted as **regular number**                                                                              | Cell auto-formatted as **regular number**                |
```

2022-12-04 23:24 UTC, warpech commented on docs/guide/list-of-differences.md
> +| TIMEVALUE function                                 | =TIMEVALUE("14:31")                                                       | Type of the returned value: `CellValueDetailedType.NUMBER_TIME` (com
```suggestion
| TIMEVALUE function                                 | =TIMEVALUE("14:31")                                                       | Type of the returned value: `CellValueDetailedType.NUMBER_TIME` (compliant with the [OpenDocument](https://docs.oasis-open.org/office/OpenDocument/v1.3/os/part4-formula/OpenDocument-v1.3-os-part4-formula.html) standard)            | Cell auto-formatted as **regular number**                                                                              | Cell auto-formatted as **regular number**                |
```

2022-12-04 23:24 UTC, warpech commented on docs/guide/list-of-differences.md
> +| EDATE function                                     | =EDATE(DATE(2019, 7, 31), 1)                                              | Type of the returned value: `CellValueDetailedType.NUMBER_DATE`
```suggestion
| EDATE function                                     | =EDATE(DATE(2019, 7, 31), 1)                                              | Type of the returned value: `CellValueDetailedType.NUMBER_DATE` (non-compliant with the [OpenDocument](https://docs.oasis-open.org/office/OpenDocument/v1.3/os/part4-formula/OpenDocument-v1.3-os-part4-formula.html) standard)            | Cell auto-formatted as **date**                                                                                        | Cell auto-formatted as **regular number**                |
```

2022-12-04 23:24 UTC, warpech commented on docs/guide/list-of-differences.md
> +| EOMONTH function                                   | =EOMONTH(DATE(2019, 7, 31), 1)                                            | Type of the returned value: `CellValueDetailedType.NUMBER_DATE`
```suggestion
| EOMONTH function                                   | =EOMONTH(DATE(2019, 7, 31), 1)                                            | Type of the returned value: `CellValueDetailedType.NUMBER_DATE` (non-compliant with the [OpenDocument](https://docs.oasis-open.org/office/OpenDocument/v1.3/os/part4-formula/OpenDocument-v1.3-os-part4-formula.html) standard)            | Cell auto-formatted as **date**                                                                                        | Cell auto-formatted as **regular number**                |
```

2022-12-06 22:26 UTC, warpech commented on docs/guide/built-in-functions.md
> +| EOMONTH          | Returns the date of the last day of a month which falls months away from the start date. Returns the value in the form of number of full days since [nullDate](../api/interfaces/c
The rendering of the duplicate footnote looks weird to me (`[1:1]`), but I guess this is some convention that I was not aware of. It is certainly better.

2022-12-06 23:05 UTC, warpech requested changes
Thank you for the edits! Some more nitpicking:

2022-12-06 23:05 UTC, warpech commented on docs/guide/list-of-differences.md
> +| EOMONTH function                                   | =EOMONTH(DATE(2019, 7, 31), 1)                                            | Type of the returned value: `CellValueDetailedType.NUMBER_DATE` (non
Here, we could soften a bit (same for EDATE):

```suggestion
| EOMONTH function                                   | =EOMONTH(DATE(2019, 7, 31), 1)                                            | Type of the returned value: `CellValueDetailedType.NUMBER_DATE`. This is non-compliant with the [OpenDocument](https://docs.oasis-open.org/office/OpenDocument/v1.3/os/part4-formula/OpenDocument-v1.3-os-part4-formula.html) standard, which defines the return type as a Number, while describing it as a Date serial number through the function summary.            | Cell auto-formatted as **date**                                                                                        | Cell auto-formatted as **regular number**                |
```

2022-12-06 23:05 UTC, warpech commented
Maybe we could contact the specification editors about this discrepancy by email, or the mailing list (there were [some questions](https://markmail.org/search/?q=EOMONTH&q=list%3Aorg.oasis-open.lists.office-comment) already), or the [issue board](https://issues.oasis-open.org/browse/OFFICE-2027?jql=text%20~%20%22eomonth%22).

2022-12-07 20:11 UTC, sequba commented on docs/guide/built-in-functions.md
> +| EDATE            | Shifts the given startdate by given number of months and returns it as the number of full days since [nullDate](../api/interfaces/configparams.md#nulldate).<br>Return type: `Cell
Changed

2022-12-07 20:12 UTC, sequba commented on docs/guide/built-in-functions.md
> +[^non-odff]: Non-compliant with the [OpenDocument](https://docs.oasis-open.org/office/OpenDocument/v1.3/os/part4-formula/OpenDocument-v1.3-os-part4-formula.html) standard. See [compatibility notes](l
I changed it to
```
[^non-odff]: The return value of this function is compliant with the [OpenDocument standard](https://docs.oasis-open.org/office/OpenDocument/v1.3/os/part4-formula/OpenDocument-v1.3-os-part4-formula.html), but the return type is not. See [compatibility notes](list-of-differences.md).
```

2022-12-07 20:48 UTC, sequba commented
@warpech 
> Maybe we could contact the specification editors about this discrepancy

I posted a question to their mailing list [office-comment@lists.oasis-open.org](mailto:office-comment@lists.oasis-open.org):

> I'm a developer working on HyperFormula - a javascript formula calculation engine: https://hyperformula.handsontable.com/
> 
> We try to follow the OpenFormula 1.3 specification: https://docs.oasis-open.org/office/OpenDocument/v1.3/os/part4-formula/OpenDocument-v1.3-os-part4-formula.html
> 
> I have a question about functions EDATE and EOMONTH. The specification states that their return type should be Number, but for me, it seems more logical to return Date from these 2 functions. The numbers returned by EDATE and EOMONTH are not "just numbers" they represent dates in the same way as in functions TODAY, DATE, etc.
> 
> Link to the discussion on that topic in our project repository: https://github.com/handsontable/hyperformula/issues/1083

2022-12-08 21:50 UTC, warpech commented on docs/guide/built-in-functions.md
> +[^non-odff]: Non-compliant with the [OpenDocument](https://docs.oasis-open.org/office/OpenDocument/v1.3/os/part4-formula/OpenDocument-v1.3-os-part4-formula.html) standard. See [compatibility notes](l
Great, thanks!

2022-12-08 23:06 UTC, warpech approved these changes
Great! Before merging, please consider a page layout improvement: https://github.com/handsontable/hyperformula/pull/1120

2022-12-09 10:41 UTC, merged