Update dependencies
handsontable/hyperformula pull request #1258
Opened 2023-04-28 09:00 UTC by sequba

### Context

TBP

### How did you test your changes?

- [ ] builds correctly
- [ ] docs build correctly
- [ ] unit tests pass

### Types of changes

- [ ] Breaking change (a fix or a feature because of which an existing functionality doesn't work as expected anymore)
- [x] New feature or improvement (a non-breaking change that adds functionality)
- [ ] Bug fix (a non-breaking change that fixes an issue)
- [ ] Additional language file, or a change to an existing language file (translations)
- [ ] Change to the documentation

### Related issues:
Fixes #1239 

### Checklist:

- [ ] I have reviewed the guidelines about [Contributing to HyperFormula](https://hyperformula.handsontable.com/guide/contributing.html) and I confirm that my code follows the code style of this project.
- [ ] I have signed the [Contributor License Agreement](https://goo.gl/forms/yuutGuN0RjsikVpM2).
- [ ] My change is compliant with the [OpenDocument](https://docs.oasis-open.org/office/OpenDocument/v1.3/os/part4-formula/OpenDocument-v1.3-os-part4-formula.html) standard.
- [ ] My change is compatible with Microsoft Excel.
- [ ] My change is compatible with Google Sheets.
- [ ] I described my changes in the [CHANGELOG.md](https://github.com/handsontable/hyperformula/blob/master/CHANGELOG.md) file.
- [ ] My changes require a documentation update.
- [ ] My changes require a migration guide.

2023-05-11 10:11 UTC, sequba commented
TODO: check if renamed interfaces are not exposed as public APIs

2023-05-18 12:49 UTC, wszymanski requested changes
It works as desired. Just one minor remark.

2023-05-18 13:26 UTC, sequba commented on .config/webpack/languages.js
> +require('string-replace-loader');
Turns out this require statement is not needed here. I removed it.

2023-05-18 14:34 UTC, wszymanski approved these changes

2023-05-18 15:22 UTC, merged