Implement new GitHub issue templates
handsontable/hyperformula pull request #1276
Opened 2023-05-23 10:01 UTC by adrianszymanski89

### Context

This PR implements new GitHub issue templates for a better user experience.

### How did you test your changes?

The templates were developed and tested in a private repository.

### Types of changes

- [ ] Breaking change (a fix or a feature because of which an existing functionality doesn't work as expected anymore)
- [X] New feature or improvement (a non-breaking change that adds functionality)
- [ ] Bug fix (a non-breaking change that fixes an issue)
- [ ] Additional language file, or a change to an existing language file (translations)
- [ ] Change to the documentation

### Related issues:
1. https://github.com/handsontable/hyperformula/issues/1274

### Checklist:

- [X] I have reviewed the guidelines about [Contributing to HyperFormula](https://hyperformula.handsontable.com/guide/contributing.html) and I confirm that my code follows the code style of this project.
- [ ] I have signed the [Contributor License Agreement](https://goo.gl/forms/yuutGuN0RjsikVpM2).
- [ ] My change is compliant with the [OpenDocument](https://docs.oasis-open.org/office/OpenDocument/v1.3/os/part4-formula/OpenDocument-v1.3-os-part4-formula.html) standard.
- [ ] My change is compatible with Microsoft Excel.
- [ ] My change is compatible with Google Sheets.
- [ ] I described my changes in the [CHANGELOG.md](https://github.com/handsontable/hyperformula/blob/master/CHANGELOG.md) file.
- [ ] My changes require a documentation update.
- [ ] My changes require a migration guide.

2023-05-23 12:40 UTC, adrianszymanski89 commented on .github/ISSUE_TEMPLATE/improve_docs.yaml
> +name: Documentation improvement
@sequba Yes, it's based on a similar project for Handsontable, but we needed to make some adjustments. We will introduce more options when Hyperformula has its own support page.

2023-05-24 08:10 UTC, sequba requested changes
@krzysztofspilka WDYT about the `other_issue` template?

2023-05-24 08:10 UTC, sequba commented on .github/ISSUE_TEMPLATE/other_issue.yaml
> +      required: true
I need a template with a few inputs to create tasks quickly.

Besides, these inputs don't really make sense for issues other than bugs.

```suggestion
```

2023-05-24 08:10 UTC, sequba commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +      description: Use StackBlitz, CodeSandbox, CodePen, JSFiddle, or any other online sandbox.
IMO this should be required. It's really hard for us to fix a bug without a demo.

```suggestion
      description: Use StackBlitz, CodeSandbox, CodePen, JSFiddle, or any other online sandbox.
    validations:
      required: true
```

2023-05-24 08:10 UTC, sequba commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +      required: true
For HyperFormula, screenshots are not that important because there is no UI. IMO it should be an optional input.

```suggestion
```

2023-05-24 08:10 UTC, sequba commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +      label: Framework version
```suggestion
      label: Framework version (e.g. React, Angular, Vue, etc)
```

2023-05-24 10:45 UTC, adrianszymanski89 commented
@sequba 

The other issue template was removed, as we discussed. A blank template will be enabled by default.

2023-05-24 11:30 UTC, sequba approved these changes

2023-05-24 12:06 UTC, merged