Create a mortgage calculator demo for the repo README
handsontable/hyperformula pull request #1387
Opened 2024-03-06 10:38 UTC by sequba

### Context

### How did you test your changes?

### Types of changes

- [ ] Breaking change (a fix or a feature because of which an existing functionality doesn't work as expected anymore)
- [ ] New feature or improvement (a non-breaking change that adds functionality)
- [ ] Bug fix (a non-breaking change that fixes an issue)
- [ ] Additional language file, or a change to an existing language file (translations)
- [ ] Change to the documentation

### Related issues:
Fixes #1380

### Checklist:

- [ ] I have reviewed the guidelines about [Contributing to HyperFormula](https://hyperformula.handsontable.com/guide/contributing.html) and I confirm that my code follows the code style of this project.
- [ ] I have signed the [Contributor License Agreement](https://goo.gl/forms/yuutGuN0RjsikVpM2).
- [ ] My change is compliant with the [OpenDocument](https://docs.oasis-open.org/office/OpenDocument/v1.3/os/part4-formula/OpenDocument-v1.3-os-part4-formula.html) standard.
- [ ] My change is compatible with Microsoft Excel.
- [ ] My change is compatible with Google Sheets.
- [ ] I described my changes in the [CHANGELOG.md](https://github.com/handsontable/hyperformula/blob/master/CHANGELOG.md) file.
- [ ] My changes require a documentation update.
- [ ] My changes require a migration guide.

2024-03-22 10:38 UTC, evanSe requested changes

2024-03-22 10:38 UTC, evanSe commented on README.md
> +hf.addNamedExpression('LoanAmount', 10000);
Lets do something more realistic 
```suggestion
hf.addNamedExpression('AnnualInterestRate', '8%');
hf.addNamedExpression('NumberOfMonths', 360);
hf.addNamedExpression('LoanAmount', 800000);
```

2024-03-26 13:48 UTC, krzysztofspilka requested changes

2024-03-26 13:48 UTC, krzysztofspilka commented on README.md
> +HyperFormula is a headless spreadsheet built in TypeScript, serving as both a parser and evaluator of spreadsheet formulas. It can be seamlessly integrated into your browser or utilized as a service
Let's remove a word `seamlessly`

2024-03-26 13:48 UTC, krzysztofspilka commented on README.md
> +HyperFormula doesn't assume any existing user interface, making it a great general-purpose library that can be used in various business applications. Here are some examples:
Let's remove a word `great`

2024-03-26 13:48 UTC, krzysztofspilka commented on README.md
>  - [Support for Node.js](https://hyperformula.handsontable.com/guide/server-side-installation.html#install-with-npm-or-yarn)
Let's make all the links on the list like this [Support for Node.js](https://hyperformula.handsontable.com/guide/server-side-installation.html#install-with-npm-or-yarn) - the entire list item should be wrapped in a link.

2024-03-26 13:48 UTC, krzysztofspilka commented on README.md
> +- Maintained by the company that stands behind the [Handsontable](https://handsontable.com/) data grid
by the company -> by the team

2024-03-26 13:48 UTC, krzysztofspilka commented on README.md
> +Please read the [Contributing Guide](https://hyperformula.handsontable.com/guide/contributing.html) before making a pull request.
Better: Contributions are welcome, but before you make them, please read the [Contributing Guide]() and accept the Contributor License Agreement.

2024-03-26 13:48 UTC, krzysztofspilka commented on README.md
> +© 2024 Handsoncode
Better: Copyright (c) Handsoncode

2024-04-02 09:10 UTC, sequba commented on README.md
TODO: copy the content of README.md to the docs main page docs/index.md.

2024-04-02 09:12 UTC, sequba commented on README.md
> +[Run this code in CodeSandbox](https://codesandbox.io/p/sandbox/github/handsontable/hyperformula-demos/tree/feature/issue-1380/mortgage-calculator)
TODO: before merging update the codesandbox link to the production one

2024-04-02 13:23 UTC, evanSe approved these changes

2024-04-04 12:41 UTC, sequba commented
@krzysztofspilka @evanSe The mortgage calculator demo in codesandbox should be fixed now.

2024-04-04 16:46 UTC, sequba commented on README.md
done

2024-04-04 16:47 UTC, sequba commented on README.md
> +[Run this code in CodeSandbox](https://codesandbox.io/p/sandbox/github/handsontable/hyperformula-demos/tree/feature/issue-1380/mortgage-calculator)
done

2024-04-04 16:48 UTC, merged