Add generic context option for custom function resolution
handsontable/hyperformula pull request #1398
Opened 2024-03-27 12:58 UTC by michaelbridge

### Context
Enable pass-through of generic parameters to underlying custom functions via `context` option. Further discussion [here](https://github.com/handsontable/hyperformula/discussions/808).

### How did you test your changes?
Added tests; ran `npm run test`

### Types of changes
- [ ] Breaking change (a fix or a feature because of which an existing functionality doesn't work as expected anymore)
- [x] New feature or improvement (a non-breaking change that adds functionality)
- [ ] Bug fix (a non-breaking change that fixes an issue)
- [ ] Additional language file, or a change to an existing language file (translations)
- [ ] Change to the documentation

### Related issues:
1. Fixes #808

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to HyperFormula](https://hyperformula.handsontable.com/guide/contributing.html) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://goo.gl/forms/yuutGuN0RjsikVpM2).
- [x] My change is compliant with the [OpenDocument](https://docs.oasis-open.org/office/OpenDocument/v1.3/os/part4-formula/OpenDocument-v1.3-os-part4-formula.html) standard.
- [x] My change is compatible with Microsoft Excel.
- [x] My change is compatible with Google Sheets.
- [x] I described my changes in the [CHANGELOG.md](https://github.com/handsontable/hyperformula/blob/master/CHANGELOG.md) file.
- [ ] My changes require a documentation update.
- [ ] My changes require a migration guide.

2024-03-28 11:50 UTC, sequba requested changes
Thank you for contributing to the HyperFormula project. Please look at my comments about the code.

2024-03-28 11:50 UTC, sequba commented on test/config.spec.ts
> +    expect(() => new Config({context: 'ABCD'})).toThrowError('Expected value of type: object for config parameter: context')
Do you think we should validate the type of the `context` parameter? In my opinion, any type should be allowed.

2024-03-28 11:50 UTC, sequba commented on test/config.spec.ts
>      const functionName = '0123456ABCDEFGH'
Please, add also a unit test that demonstrates the purpose of the `context` parameter. Create a custom function that uses the provided data. You may have a look at `test/custom-functions.spec.ts` to see how to create a custom function inside a test file.

2024-03-28 11:50 UTC, sequba commented on src/Config.ts
> +   * @default {}
```suggestion
   * @default undefined
```

2024-03-28 11:50 UTC, sequba commented on src/Config.ts
> +    context: {},
```suggestion
    context: undefined,
```

2024-03-28 11:50 UTC, sequba commented on src/Config.ts
> +  public readonly context: Record<string, unknown>
```suggestion
  public readonly context: unknown
```

2024-03-28 16:01 UTC, sequba approved these changes

2024-03-28 16:03 UTC, sequba approved these changes
Good job! After @evanSe approval, it can be merged to `develop` and released with the next version fo HyperFormula.

2024-04-03 09:14 UTC, evanSe approved these changes

2024-04-03 11:12 UTC, merged

2024-04-03 11:13 UTC, sequba commented
Merging to temporary branch `feature/issue-1396` to resolve conflicts with `develop`