XLOOKUP function
handsontable/hyperformula pull request #1469
Opened 2024-12-05 16:48 UTC by sequba

### Context

### How did you test your changes?

### Types of changes

- [ ] Breaking change (a fix or a feature because of which an existing functionality doesn't work as expected anymore)
- [ ] New feature or improvement (a non-breaking change that adds functionality)
- [ ] Bug fix (a non-breaking change that fixes an issue)
- [ ] Additional language file, or a change to an existing language file (translations)
- [ ] Change to the documentation

### Related issues:
1. Fixes #...
2.
3.

### Checklist:

- [ ] I have reviewed the guidelines about [Contributing to HyperFormula](https://hyperformula.handsontable.com/guide/contributing.html) and I confirm that my code follows the code style of this project.
- [ ] I have signed the [Contributor License Agreement](https://goo.gl/forms/yuutGuN0RjsikVpM2).
- [ ] My change is compliant with the [OpenDocument](https://docs.oasis-open.org/office/OpenDocument/v1.3/os/part4-formula/OpenDocument-v1.3-os-part4-formula.html) standard.
- [ ] My change is compatible with Microsoft Excel.
- [ ] My change is compatible with Google Sheets.
- [ ] I described my changes in the [CHANGELOG.md](https://github.com/handsontable/hyperformula/blob/master/CHANGELOG.md) file.
- [ ] My changes require a documentation update.
- [ ] My changes require a migration guide.

2025-01-02 12:24 UTC, budnix requested changes
I'm not an expert in HF but it looks good to me. I only found a typo that worth to fix.

2025-01-02 12:24 UTC, budnix commented on src/Lookup/AdvancedFind.ts
> +  public advancedFind(keyMatcher: (arg: RawInterpreterValue) => boolean, rangeValue: SimpleRangeValue, { returnOccurence }: AdvancedFindOptions = { returnOccurence: 'first' }): number {
a typo :) 
```suggestion
  public advancedFind(keyMatcher: (arg: RawInterpreterValue) => boolean, rangeValue: SimpleRangeValue, { returnOccurence }: AdvancedFindOptions = { returnOccurrence: 'first' }): number {
```

2025-01-02 12:24 UTC, budnix commented on src/Lookup/ColumnIndex.ts
> +  public find(searchKey: RawNoErrorScalarValue, rangeValue: SimpleRangeValue, { ordering, ifNoMatch, returnOccurence }: SearchOptions): number {
```suggestion
  public find(searchKey: RawNoErrorScalarValue, rangeValue: SimpleRangeValue, { ordering, ifNoMatch, returnOccurrence }: SearchOptions): number {
```

2025-01-02 12:24 UTC, budnix commented on src/Lookup/ColumnIndex.ts
> +  private findUsingColumnIndex(key: RawNoErrorScalarValue, rangeValue: SimpleRangeValue, returnOccurence: 'first' | 'last'): Maybe<number> {
```suggestion
  private findUsingColumnIndex(key: RawNoErrorScalarValue, rangeValue: SimpleRangeValue, returnOccurrence: 'first' | 'last'): Maybe<number> {
```

2025-01-02 12:24 UTC, budnix commented on src/Lookup/ColumnIndex.ts
> +  private static findRowBelongingToRange(valueIndex: ValueIndex, range: AbsoluteCellRange, returnOccurence: 'first' | 'last'): Maybe<number> {
```suggestion
  private static findRowBelongingToRange(valueIndex: ValueIndex, range: AbsoluteCellRange, returnOccurrence: 'first' | 'last'): Maybe<number> {
```

2025-01-02 12:24 UTC, budnix commented on src/Lookup/ColumnIndex.ts
> +  public advancedFind(keyMatcher: (arg: RawInterpreterValue) => boolean, range: SimpleRangeValue, options: AdvancedFindOptions = { returnOccurence: 'first' }): number {
```suggestion
  public advancedFind(keyMatcher: (arg: RawInterpreterValue) => boolean, range: SimpleRangeValue, options: AdvancedFindOptions = { returnOccurrence: 'first' }): number {
```

2025-01-02 12:24 UTC, budnix commented on src/Lookup/SearchStrategy.ts
> +  returnOccurence?: 'first' | 'last',
```suggestion
  returnOccurrence?: 'first' | 'last',
}

export interface AdvancedFindOptions {
  returnOccurrence?: 'first' | 'last',
```

2025-01-02 16:10 UTC, sequba commented on src/Lookup/AdvancedFind.ts
> +  public advancedFind(keyMatcher: (arg: RawInterpreterValue) => boolean, rangeValue: SimpleRangeValue, { returnOccurence }: AdvancedFindOptions = { returnOccurence: 'first' }): number {
Thanks @budnix, great catch. I changed every occurrence of "occurence" (single r).

2025-01-03 08:36 UTC, budnix approved these changes

2025-01-03 11:00 UTC, merged