statistical functions
handsontable/hyperformula pull request #564
Opened 2020-11-05 16:46 UTC by izulin

### Context

### How has this been tested?

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1.
2.
3.

### Checklist:

- [ ] My code follows the code style of this project,
- [ ] My change requires a change to the documentation,
- [ ] I described the modification in the CHANGELOG.md file.

2020-11-11 23:33 UTC, wojciechczerniak requested changes

2020-11-11 23:58 UTC, izulin commented on CHANGELOG.md
> +- Added 32 statistical functions F.DIST, F.DIST.RT, F.INV, F.INV.RT, FDIST, FINV, WEIBULL, WEIBULL.DIST, HYPGEOMDIST, HYPGEOM.DIST, T.DIST, T.DIST.2T, T.DIST.RT, T.INV, T.INV.2T, TDIST, TINV, LOGNORM
Hmmm, right

2020-11-12 10:34 UTC, izulin commented on test/interpreter/function-hypgeom.dist.spec.ts
> +      ['=HYPGEOM.DIST(10.9, 21, 20, 30.9, TRUE())'],
we test first arg for <= 0. We test second/third arg for <= first arg. We test fourth arg for <= second/third. There is no way to write test where second/third/fourth arg is <= 0 without violating those conditions or making first arg <= 0.

2020-11-12 15:45 UTC, wojciechczerniak commented on test/interpreter/function-hypgeom.dist.spec.ts
> +      ['=HYPGEOM.DIST(10.9, 21, 20, 30.9, TRUE())'],
👍

2020-11-12 15:46 UTC, wojciechczerniak approved these changes
Thx 👍

2020-11-12 23:22 UTC, bardek8 requested changes
Thanks a lot!
Actually the only issue is with (in)compatibility with XL/GS, as they behave differently in the corner (out of bound) cases. You'll know best what is the desired behavior then, but I marked in comments all places that are different.

2020-11-12 23:22 UTC, bardek8 commented on test/interpreter/function-hypgeom.dist.spec.ts
> +    expect(engine.getCellValue(adr('A4'))).toEqualError(detailedError(ErrorType.NUM, ErrorMessage.ValueLarge))
XL returns 1 here

2020-11-12 23:22 UTC, bardek8 commented on test/interpreter/function-hypgeom.dist.spec.ts
> +    expect(engine.getCellValue(adr('A6'))).toEqualError(detailedError(ErrorType.NUM, ErrorMessage.ValueLarge))
and here

2020-11-12 23:22 UTC, bardek8 commented on test/interpreter/function-hypgeom.dist.spec.ts
> +    expect(engine.getCellValue(adr('A12'))).toEqualError(detailedError(ErrorType.NUM, ErrorMessage.ValueLarge))
XL accepts it

2020-11-12 23:22 UTC, bardek8 commented on test/interpreter/function-negbinom.dist.spec.ts
> +    expect(engine.getCellValue(adr('A4'))).toEqual(0)
XL returns error here

2020-11-12 23:22 UTC, bardek8 commented on test/interpreter/function-negbinom.dist.spec.ts
> +    expect(engine.getCellValue(adr('A6'))).toEqual(1)
and here

2020-11-12 23:22 UTC, bardek8 commented on test/interpreter/function-poisson.dist.spec.ts
> +      ['=POISSON.DIST(0, -0.01, FALSE())'],
XL accepts here

2020-11-12 23:22 UTC, bardek8 commented on test/interpreter/function-t.dist.spec.ts
> +    expect(engine.getCellValue(adr('A2'))).toEqualError(detailedError(ErrorType.NUM, ErrorMessage.ValueSmall))
interesting, XL says DIV/0 here

2020-11-12 23:22 UTC, bardek8 commented on test/interpreter/function-t.inv.2t.spec.ts
> +    expect(engine.getCellValue(adr('A2'))).toEqualError(detailedError(ErrorType.NUM, ErrorMessage.ValueSmall))
XL returns DIV/0

2020-11-12 23:22 UTC, bardek8 commented on test/interpreter/function-t.inv.2t.spec.ts
> +    expect(engine.getCellValue(adr('A4'))).toEqualError(detailedError(ErrorType.NUM, ErrorMessage.ValueLarge))
XL accepts

2020-11-12 23:22 UTC, bardek8 commented on test/interpreter/function-t.inv.spec.ts
> +    expect(engine.getCellValue(adr('A2'))).toEqualError(detailedError(ErrorType.NUM, ErrorMessage.ValueSmall))
DIV/0 in XL

2020-11-12 23:22 UTC, bardek8 commented on test/interpreter/function-tdist.spec.ts
> +    expect(engine.getCellValue(adr('A7'))).toEqualError(detailedError(ErrorType.NUM, ErrorMessage.IntegerExpected))
XL accepts

2020-11-12 23:22 UTC, bardek8 commented on test/interpreter/function-weibull.dist.spec.ts
> +    expect(engine.getCellValue(adr('A1'))).toEqual(1)
hm, XL returns 0 here, GS 1

2020-11-12 23:24 UTC, bardek8 commented on test/interpreter/function-hypgeom.dist.spec.ts
> +  //In product #1, function takes 4 arguments.
WDYT - in such situations the note above each different test would be too much clutter? The comment at the top can be easily missed

2020-11-13 13:54 UTC, bardek8 approved these changes
Thanks for the comments!

2020-11-13 14:26 UTC, merged