Pu/vectorization
handsontable/hyperformula pull request #673
Opened 2021-05-18 12:47 UTC by izulin

### Context

Vectorization of scalar functions.

### How has this been tested?

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1.
2.
3.

### Checklist:

- [x] My code follows the code style of this project,
- [ ] My change requires a change to the documentation,
- [x] I described the modification in the CHANGELOG.md file.

2021-05-25 10:40 UTC, izulin commented on CHANGELOG.md
> +- **Breaking change**: Removed numeric matrix detection along with matrixDetection and matrixDetectionThreshold config options. (#669)
```suggestion
- Changed SWITCH function so it takes array as its first argument.
- **Breaking change**: Removed numeric matrix detection along with matrixDetection and matrixDetectionThreshold config options. (#669)
```

2021-05-27 14:22 UTC, wojciechczerniak requested changes

2021-05-27 18:20 UTC, izulin commented on src/interpreter/plugin/FunctionPlugin.ts
> +  vectorizationForbidden?: boolean,
There are subtle differences between parameters that are used by the core engine, and parameters that are just a guiding info for our wrappers.
That is, unless the custom function is written in a manner that supports vectorization, NOT setting `vectorizationForbidden` will not produce valid result anyway.

2021-05-27 18:44 UTC, wojciechczerniak commented on src/interpreter/plugin/FunctionPlugin.ts
> +  vectorizationForbidden?: boolean,
And yet, all those parameters may be used for custom function, right?

2021-05-27 19:10 UTC, izulin commented on src/interpreter/plugin/FunctionPlugin.ts
> +  vectorizationForbidden?: boolean,
Yes, they are all passed. But some of those have no effect unless explicitly used by the function implementation.

2021-05-28 12:45 UTC, wojciechczerniak approved these changes
👍

2021-05-28 12:46 UTC, merged