passes all tests
handsontable/hyperformula pull request #766
Opened 2021-07-13 15:52 UTC by izulin

### Context

Introduces plugginable arraySize checks.

WIP (tests missing, docs missing, exports missing)

### How has this been tested?

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #760 
2.
3.

### Checklist:

- [x] My code follows the code style of this project,
- [ ] My change requires a change to the documentation,
- [ ] I described the modification in the CHANGELOG.md file.

2021-07-13 23:46 UTC, izulin commented
I believe there are no exports to be added.

2021-07-14 12:03 UTC, wojciechczerniak requested changes
- This PR should add a section to docs but #741 is not yet merged. We have to wait

OMG, all those changes in visibility of interfaces 🙈 Dependency Injection could help

2021-07-14 12:03 UTC, wojciechczerniak commented on src/interpreter/ArithmeticHelper.ts
>      private readonly numberLiteralsHelper: NumberLiteralHelper,
Why not make both public? If this is the recommended way to use them, they should be available

2021-07-14 12:05 UTC, izulin commented on src/interpreter/plugin/BooleanPlugin.ts
> +  // }
right

2021-07-14 12:06 UTC, izulin commented on src/interpreter/Interpreter.ts
> +    public readonly dateTimeHelper: DateTimeHelper
both classes are quite spacious in volume and separated in logic

2021-07-14 12:22 UTC, wojciechczerniak commented on src/interpreter/Interpreter.ts
> +    public readonly dateTimeHelper: DateTimeHelper
But we have access to `arithmeticHelper` that gives access to `dateTimeHelper` to `this.dateTimeHelper` isn't the same as `this.arithmeticHelper.dateTimeHelper` and we don't have to pass both args? If no then ok

2021-07-14 12:39 UTC, izulin commented on src/interpreter/Interpreter.ts
> +    public readonly dateTimeHelper: DateTimeHelper
I did a cleanup (in this PR), where objects explicitly used by major objects are passed explicitly, not extracted from other objects.
Helps when e.g. creating mocks where some args are `undefined`.

2021-07-14 12:42 UTC, izulin commented on src/interpreter/plugin/MatrixPlugin.ts
> +}
inlined the first one, which is used once.
The others are useful, even if just for 2 or 3 usages in this plugin.

2021-07-14 12:43 UTC, izulin commented
> OMG, all those changes in visibility of interfaces 🙈 Dependency Injection could help

All those interfaces should never be accessed by the end-user, and were made public only for internal usage.

2021-07-14 12:51 UTC, izulin commented
> >Dependency Injection could help

Ok, I just educated myself on what Dependency Injection is, and AFAIR this is what I was striving for with the refactor.

2021-07-14 18:31 UTC, wojciechczerniak commented on src/interpreter/plugin/MatrixPlugin.ts
> +}
I don't see more than 1 usage 🤔

2021-07-14 18:32 UTC, wojciechczerniak approved these changes
Thanks for addressing all my concerns. LGTM 👍

2021-07-14 20:11 UTC, merged