Pu/destructors
handsontable/hyperformula pull request #786
Opened 2021-07-28 14:42 UTC by izulin

### Context

Introduces destructors for basic components of the project.

### How has this been tested?

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #775 
2.
3.

### Checklist:

- [x] My code follows the code style of this project,
- [ ] My change requires a change to the documentation,
- [ ] I described the modification in the CHANGELOG.md file.

2021-07-28 14:43 UTC, izulin commented on jest.config.js
> +  silent: false,
```suggestion
  silent: true,
```

2021-08-04 16:23 UTC, wojciechczerniak commented
To much of complexity. JavaScript should handle destruction just fine in GC cyle. It is faster than #788 but IMO not worth it. Final result of cleanup is exactly the same. I propose to close this PR and focus on #788

2021-08-04 16:24 UTC, izulin commented
> To much of complexity. JavaScript should handle destruction just fine in GC cyle. It is faster than #788 but IMO not worth it. Final result of cleanup is exactly the same. I propose to close this PR and focus on #788

Ok!

2021-08-04 16:24 UTC, closed without merging

2021-08-04 16:24 UTC, wojciechczerniak requested changes
To much of complexity. JavaScript should handle destruction just fine in GC cyle. It is faster than #788 but IMO not worth it. Final result of cleanup is exactly the same. I propose to close this PR and focus on #788