Document inline arrays and more unit tests
handsontable/hyperformula pull request #985
Opened 2022-04-26 13:47 UTC by sequba

### Context

Improve the documentation of inline arrays according to #982 and #984 

### How has this been tested?

build works, unit tests pass

### Types of changes

- [x] Documentation change

### Related issue(s):
1. Fixes #984 
2. #982 
3.

### Checklist:

- [x] My code follows the code style of this project,
- [ ] My change requires a change to the documentation,
- [ ] I described the modification in the CHANGELOG.md file.

2022-04-26 13:56 UTC, sequba commented on docs/guide/arrays.md
> +**Important: An inline array is never recomputed after initialization. If it contains a cell reference, an inline array will not be updated when the value of the cell changes.**
@kirszenbaum Any tips on better wordings?

2022-05-04 10:02 UTC, kirszenbaum requested changes

2022-05-04 10:02 UTC, kirszenbaum commented on docs/guide/known-limitations.md
> +| Cell references inside inline arrays               | ={A1, A2}                                                                 | Array value calculated but not updated on cell values changes.
```suggestion
| Cell references inside inline arrays               | ={A1, A2}                                                                 | The array's value is calculated but not updated when the cells' values change.                                                                                                                                                                                                                                         | The array's value is calculated and updated when the cells' values change.                                                                        | ERROR: invalid array                                    |
```

2022-05-04 10:02 UTC, kirszenbaum commented on docs/guide/arrays.md
> +**Important: An inline array is never recomputed after initialization. If it contains a cell reference, an inline array will not be updated when the value of the cell changes.**
@sequba - I added my ideas

2022-05-04 16:50 UTC, sequba commented on docs/guide/arrays.md
> +```
Great! Thanks a lot @kirszenbaum

2022-05-04 16:54 UTC, sequba commented on docs/guide/arrays.md
> +**Important: An inline array is never recomputed after initialization. If it contains a cell reference, an inline array will not be updated when the value of the cell changes.**
Thanks a lot @kirszenbaum

2022-05-04 16:54 UTC, sequba commented on docs/guide/known-limitations.md
> +| Cell references inside inline arrays               | ={A1, A2}                                                                 | Array value calculated but not updated on cell values changes.
Suggestion applied

2022-05-04 16:54 UTC, sequba commented on docs/guide/arrays.md
> +* An **inline array**: an ad-hoc array not referring to any range of cells (e.g. `{1,3,5}`)
Suggestions applied

2022-05-05 16:22 UTC, kirszenbaum approved these changes

2022-05-05 17:55 UTC, merged